### ISSUE TITLE
No homestead statistics when using homestead-prov instead of HSS

### ISSUE THREAD

**Issue by dtheobald** [Metaswitch/clearwater-snmp-handlers#35] opened 2015-01-12 18:52 UTC
When I run traffic and I try to walk all homestead statistics, all I get is this:
```
$ snmpwalk -v2c -c clearwater homestead-1m.vm4.richlab.datcon.co.uk 1.2.826.0.1.1578918.9
iso.2.826.0.1.1578918.9 = No Such Object available on this agent at this OID
$ snmpwalk -v2c -c clearwater homestead-2m.vm4.richlab.datcon.co.uk 1.2.826.0.1.1578918.9
iso.2.826.0.1.1578918.9 = No Such Object available on this agent at this OID
$  
```
syslog contains entries like this:
```
Jan 12 11:41:19 homestead-1 snmpd[11079]: Connection from UDP: [192.168.161.12]:13667->[192.168.163.132]:161
Jan 12 12:33:49 homestead-1 snmpd[11079]: Connection from UDP: [192.168.161.12]:8166->[192.168.163.132]:161
Jan 12 11:41:19 homestead-1 homestead_handler[11083]: Ignoring request because data out of date (1421084479 ? 0)
Jan 12 12:33:49 homestead-1 homestead_handler[11083]: Ignoring request because data out of date (1421087629 ? 0)
```

**Comment by mirw** [comment] 2015-01-12 18:58
@dtheobald, as discussed, please can you check whether you get the non-HSS statistics reported correctly when running on an HSS-enabled Homestead?

**Comment by dtheobald** [comment] 2015-01-12 19:48
More data:

With homestead-prov
```
+ snmpwalk -v2c -c clearwater 192.168.163.132 iso.2.826.0.1.1578918.9.5.1.1.2
iso.2.826.0.1.1578918.9.5.1.1.2 = No Such Instance currently exists at this OID
+ snmpwalk -v2c -c clearwater 192.168.163.132 iso.2.826.0.1.1578918.9.5.1.1.3
iso.2.826.0.1.1578918.9.5.1.1.3 = No Such Instance currently exists at this OID
+ snmpwalk -v2c -c clearwater 192.168.163.132 iso.2.826.0.1.1578918.9.5.1.1.4
iso.2.826.0.1.1578918.9.5.1.1.4 = No Such Instance currently exists at this OID
+ snmpwalk -v2c -c clearwater 192.168.163.132 iso.2.826.0.1.1578918.9.5.1.1.5
iso.2.826.0.1.1578918.9.5.1.1.5 = No Such Instance currently exists at this OID
+ snmpwalk -v2c -c clearwater 192.168.163.132 iso.2.826.0.1.1578918.9.5.1.1.6
iso.2.826.0.1.1578918.9.5.1.1.6 = No Such Instance currently exists at this OID
+ snmpwalk -v2c -c clearwater 192.168.163.132 iso.2.826.0.1.1578918.9.5.2.1.2
iso.2.826.0.1.1578918.9.5.2.1.2 = No Such Instance currently exists at this OID
+ snmpwalk -v2c -c clearwater 192.168.163.132 iso.2.826.0.1.1578918.9.5.2.1.3
iso.2.826.0.1.1578918.9.5.2.1.3 = No Such Instance currently exists at this OID
+ snmpwalk -v2c -c clearwater 192.168.163.132 iso.2.826.0.1.1578918.9.5.2.1.4
iso.2.826.0.1.1578918.9.5.2.1.4 = No Such Instance currently exists at this OID
+ snmpwalk -v2c -c clearwater 192.168.163.132 iso.2.826.0.1.1578918.9.5.2.1.5
iso.2.826.0.1.1578918.9.5.2.1.5 = No Such Instance currently exists at this OID
+ snmpwalk -v2c -c clearwater 192.168.163.132 iso.2.826.0.1.1578918.9.5.2.1.6
iso.2.826.0.1.1578918.9.5.2.1.6 = No Such Instance currently exists at this OID
+ snmpwalk -v2c -c clearwater 192.168.163.132 iso.2.826.0.1.1578918.9.5.3.1.2
iso.2.826.0.1.1578918.9.5.3.1.2 = No Such Instance currently exists at this OID
+ snmpwalk -v2c -c clearwater 192.168.163.132 iso.2.826.0.1.1578918.9.5.3.1.3
iso.2.826.0.1.1578918.9.5.3.1.3 = No Such Instance currently exists at this OID
+ snmpwalk -v2c -c clearwater 192.168.163.132 iso.2.826.0.1.1578918.9.5.3.1.4
iso.2.826.0.1.1578918.9.5.3.1.4 = No Such Instance currently exists at this OID
+ snmpwalk -v2c -c clearwater 192.168.163.132 iso.2.826.0.1.1578918.9.5.3.1.5
iso.2.826.0.1.1578918.9.5.3.1.5 = No Such Instance currently exists at this OID
+ snmpwalk -v2c -c clearwater 192.168.163.132 iso.2.826.0.1.1578918.9.5.3.1.6
iso.2.826.0.1.1578918.9.5.3.1.6 = No Such Instance currently exists at this OID
+ snmpwalk -v2c -c clearwater 192.168.163.132 iso.2.826.0.1.1578918.9.5.4.1.2
iso.2.826.0.1.1578918.9.5.4.1.2 = No Such Instance currently exists at this OID
+ snmpwalk -v2c -c clearwater 192.168.163.132 iso.2.826.0.1.1578918.9.5.4.1.3
iso.2.826.0.1.1578918.9.5.4.1.3 = No Such Instance currently exists at this OID
+ snmpwalk -v2c -c clearwater 192.168.163.132 iso.2.826.0.1.1578918.9.5.4.1.4
iso.2.826.0.1.1578918.9.5.4.1.4 = No Such Instance currently exists at this OID
+ snmpwalk -v2c -c clearwater 192.168.163.132 iso.2.826.0.1.1578918.9.5.4.1.5
iso.2.826.0.1.1578918.9.5.4.1.5 = No Such Instance currently exists at this OID
+ snmpwalk -v2c -c clearwater 192.168.163.132 iso.2.826.0.1.1578918.9.5.4.1.6
iso.2.826.0.1.1578918.9.5.4.1.6 = No Such Instance currently exists at this OID
+ snmpwalk -v2c -c clearwater 192.168.163.132 iso.2.826.0.1.1578918.9.5.5.1.2
iso.2.826.0.1.1578918.9.5.5.1.2 = No Such Instance currently exists at this OID
+ snmpwalk -v2c -c clearwater 192.168.163.132 iso.2.826.0.1.1578918.9.5.5.1.3
iso.2.826.0.1.1578918.9.5.5.1.3 = No Such Instance currently exists at this OID
+ snmpwalk -v2c -c clearwater 192.168.163.132 iso.2.826.0.1.1578918.9.5.5.1.4
iso.2.826.0.1.1578918.9.5.5.1.4 = No Such Instance currently exists at this OID
+ snmpwalk -v2c -c clearwater 192.168.163.132 iso.2.826.0.1.1578918.9.5.5.1.5
iso.2.826.0.1.1578918.9.5.5.1.5 = No Such Instance currently exists at this OID
+ snmpwalk -v2c -c clearwater 192.168.163.132 iso.2.826.0.1.1578918.9.5.5.1.6
iso.2.826.0.1.1578918.9.5.5.1.6 = No Such Instance currently exists at this OID
+ snmpwalk -v2c -c clearwater 192.168.163.132 iso.2.826.0.1.1578918.9.5.6.1.2
iso.2.826.0.1.1578918.9.5.6.1.2 = No Such Instance currently exists at this OID


With an HSS:
```
root@ip-10-0-22-39:/var/tmp/ccst# bash -x ./stats homestead-1.x.doug.core.clearwater.metaswitch.com
+ snmpwalk -v2c -c clearwater homestead-1.x.doug.core.clearwater.metaswitch.com iso.2.826.0.1.1578918.9.5.1.1.2
iso.2.826.0.1.1578918.9.5.1.1.2 = Gauge32: 26259
+ snmpwalk -v2c -c clearwater homestead-1.x.doug.core.clearwater.metaswitch.com iso.2.826.0.1.1578918.9.5.1.1.3
iso.2.826.0.1.1578918.9.5.1.1.3 = Gauge32: 900840947
+ snmpwalk -v2c -c clearwater homestead-1.x.doug.core.clearwater.metaswitch.com iso.2.826.0.1.1578918.9.5.1.1.4
iso.2.826.0.1.1578918.9.5.1.1.4 = Gauge32: 119362
+ snmpwalk -v2c -c clearwater homestead-1.x.doug.core.clearwater.metaswitch.com iso.2.826.0.1.1578918.9.5.1.1.5
iso.2.826.0.1.1578918.9.5.1.1.5 = Gauge32: 47
+ snmpwalk -v2c -c clearwater homestead-1.x.doug.core.clearwater.metaswitch.com iso.2.826.0.1.1578918.9.5.1.1.6
iso.2.826.0.1.1578918.9.5.1.1.6 = Gauge32: 16
+ snmpwalk -v2c -c clearwater homestead-1.x.doug.core.clearwater.metaswitch.com iso.2.826.0.1.1578918.9.5.2.1.2
iso.2.826.0.1.1578918.9.5.2.1.2 = Gauge32: 21457
+ snmpwalk -v2c -c clearwater homestead-1.x.doug.core.clearwater.metaswitch.com iso.2.826.0.1.1578918.9.5.2.1.3
iso.2.826.0.1.1578918.9.5.2.1.3 = Gauge32: 185613376
+ snmpwalk -v2c -c clearwater homestead-1.x.doug.core.clearwater.metaswitch.com iso.2.826.0.1.1578918.9.5.2.1.4
iso.2.826.0.1.1578918.9.5.2.1.4 = Gauge32: 35081
+ snmpwalk -v2c -c clearwater homestead-1.x.doug.core.clearwater.metaswitch.com iso.2.826.0.1.1578918.9.5.2.1.5
iso.2.826.0.1.1578918.9.5.2.1.5 = Gauge32: 7833
+ snmpwalk -v2c -c clearwater homestead-1.x.doug.core.clearwater.metaswitch.com iso.2.826.0.1.1578918.9.5.2.1.6
iso.2.826.0.1.1578918.9.5.2.1.6 = Gauge32: 12
+ snmpwalk -v2c -c clearwater homestead-1.x.doug.core.clearwater.metaswitch.com iso.2.826.0.1.1578918.9.5.3.1.2
iso.2.826.0.1.1578918.9.5.3.1.2 = Gauge32: 6568
+ snmpwalk -v2c -c clearwater homestead-1.x.doug.core.clearwater.metaswitch.com iso.2.826.0.1.1578918.9.5.3.1.3
iso.2.826.0.1.1578918.9.5.3.1.3 = Gauge32: 59678430
+ snmpwalk -v2c -c clearwater homestead-1.x.doug.core.clearwater.metaswitch.com iso.2.826.0.1.1578918.9.5.3.1.4
iso.2.826.0.1.1578918.9.5.3.1.4 = Gauge32: 26496
+ snmpwalk -v2c -c clearwater homestead-1.x.doug.core.clearwater.metaswitch.com iso.2.826.0.1.1578918.9.5.3.1.5
iso.2.826.0.1.1578918.9.5.3.1.5 = Gauge32: 2179
+ snmpwalk -v2c -c clearwater homestead-1.x.doug.core.clearwater.metaswitch.com iso.2.826.0.1.1578918.9.5.3.1.6
iso.2.826.0.1.1578918.9.5.3.1.6 = Gauge32: 9
+ snmpwalk -v2c -c clearwater homestead-1.x.doug.core.clearwater.metaswitch.com iso.2.826.0.1.1578918.9.5.4.1.2
iso.2.826.0.1.1578918.9.5.4.1.2 = Gauge32: 42112
+ snmpwalk -v2c -c clearwater homestead-1.x.doug.core.clearwater.metaswitch.com iso.2.826.0.1.1578918.9.5.4.1.3
iso.2.826.0.1.1578918.9.5.4.1.3 = Gauge32: 0
+ snmpwalk -v2c -c clearwater homestead-1.x.doug.core.clearwater.metaswitch.com iso.2.826.0.1.1578918.9.5.4.1.4
iso.2.826.0.1.1578918.9.5.4.1.4 = Gauge32: 42112
+ snmpwalk -v2c -c clearwater homestead-1.x.doug.core.clearwater.metaswitch.com iso.2.826.0.1.1578918.9.5.4.1.5
iso.2.826.0.1.1578918.9.5.4.1.5 = Gauge32: 42112
+ snmpwalk -v2c -c clearwater homestead-1.x.doug.core.clearwater.metaswitch.com iso.2.826.0.1.1578918.9.5.4.1.6
iso.2.826.0.1.1578918.9.5.4.1.6 = Gauge32: 363
+ snmpwalk -v2c -c clearwater homestead-1.x.doug.core.clearwater.metaswitch.com iso.2.826.0.1.1578918.9.5.5.1.2
iso.2.826.0.1.1578918.9.5.5.1.2 = Gauge32: 21457
+ snmpwalk -v2c -c clearwater homestead-1.x.doug.core.clearwater.metaswitch.com iso.2.826.0.1.1578918.9.5.5.1.3
iso.2.826.0.1.1578918.9.5.5.1.3 = Gauge32: 185613376
+ snmpwalk -v2c -c clearwater homestead-1.x.doug.core.clearwater.metaswitch.com iso.2.826.0.1.1578918.9.5.5.1.4
iso.2.826.0.1.1578918.9.5.5.1.4 = Gauge32: 35081
+ snmpwalk -v2c -c clearwater homestead-1.x.doug.core.clearwater.metaswitch.com iso.2.826.0.1.1578918.9.5.5.1.5
iso.2.826.0.1.1578918.9.5.5.1.5 = Gauge32: 7833
+ snmpwalk -v2c -c clearwater homestead-1.x.doug.core.clearwater.metaswitch.com iso.2.826.0.1.1578918.9.5.5.1.6
iso.2.826.0.1.1578918.9.5.5.1.6 = Gauge32: 12
+ snmpwalk -v2c -c clearwater homestead-1.x.doug.core.clearwater.metaswitch.com iso.2.826.0.1.1578918.9.5.6.1.2
iso.2.826.0.1.1578918.9.5.6.1.2 = Gauge32: 6
root@ip-10-0-22-39:/var/tmp/ccst# 
```

**Comment by mirw** [comment] 2015-01-13 20:34
I've been investigating this.  It's looking pretty hairy.

First thing to say is: it doesn't look as though it's down to HSS vs no-HSS - I've seen this working on a no-HSS system.

The simplest behavior that I've seen is as follows.

*   homestead is running, bound to one instance of `/var/run/clearwater/stats/homestead` to provide statistics.

*   A second homestead is started.  It obviously can't start up fully (at the very least, it will fail to bind port 8888) but it does get far enough to delete and replace `/var/run/clearwater/stats/homestead` with a new instance before it dies.  (The original homestead process is still bound to the original, independent instance.)

*   snmpd starts (or is restarted) and cyclically tries to connect to the new `/var/run/clearwater/stats/homestead`, failing because there's nothing listening at the other end.

*   snmpd serves SNMP requests, but clearly doesn't have any statistics to report.

*   Restarting snmpd doesn't fix the problem, but restarting homestead does.

The more complicated scenario I've seen is as above, but snmpd appears to have successfully connected to the new `/var/run/clearwater/stats/homestead` unix socket.  As a result, first homestead and then snmpd must be restarted before statistics start to be reported.

@dtheobald, if you restart snmpd, does that clear the problem for you?  If not, does restarting homestead and then snmpd (in that order, with a few seconds between the commands) clear the problem?

**Comment by mirw** [comment] 2015-01-13 20:37
A note on useful tools here.

*   `strace` allows you to identify the file descriptors that we're connecting with, and see whether or not we're actively sending or receiving.
*   `lsof` translates these into inodes - the inodes at either end of a unix domain socket will (almost always?) be 1 different.
*   `stat` gives the inode of files on disk - a listening socket will (almost always?) be 1 different from the socket that's bound to it.

**Comment by dtheobald** [comment] 2015-01-13 22:37
After restarting homestead's snmpd, I see statistics from homestead. Strangely, I've also noticed that sprout stats weren't changing, so I restarted sprout's snmpd and some of the stats started changing. However, some stats seemed to hang around for a while (minute+). For instance:
```
snmpwalk -v2c -c clearwater sprout-1m.vm4.richlab.datcon.co.uk PROJECT-CLEARWATER-MIB::sprout|grep MARLatency
MIB search path: /home/ccst/.snmp/mibs:/usr/share/mibs/site:/usr/share/snmp/mibs:/usr/share/mibs/iana:/usr/share/mibs/ietf:/usr/share/mibs/netsnmp
Cannot find module (INET-ADDRESS-MIB): At line 6 in /home/ccst/.snmp/mibs/PROJECT-CLEARWATER-MIB.txt
Did not find 'InetAddressType' in module #-1 (/home/ccst/.snmp/mibs/PROJECT-CLEARWATER-MIB.txt)
Did not find 'InetAddress' in module #-1 (/home/ccst/.snmp/mibs/PROJECT-CLEARWATER-MIB.txt)
PROJECT-CLEARWATER-MIB::sproutMARLatencyAverage = Gauge32: 1292
PROJECT-CLEARWATER-MIB::sproutMARLatencyVariance = Gauge32: 81279
PROJECT-CLEARWATER-MIB::sproutMARLatencyHWM = Gauge32: 2313
PROJECT-CLEARWATER-MIB::sproutMARLatencyLWM = Gauge32: 909
PROJECT-CLEARWATER-MIB::sproutMARLatencyCount = Gauge32: 960
[sipp]ccst@richsiptest1:~/ccst$ 
```

**Comment by mirw** [comment] 2015-01-19 14:41
@AlexHockey, as discussed you're going to pick this up.

**Comment by AlexHockey** [comment] 2015-01-19 19:36
Finally managed to reproduce this after being held up by https://github.com/Metaswitch/clearwater-snmp-handlers/issues/28, https://github.com/Metaswitch/clearwater-infrastructure/issues/127 and my own stupidity. 

I discussed fixes with Matt. The problem occurs because the second homestead that is started unlinks the named socket prior to binding. We can't see a reason why this is needed. A simple solution may be to not do this. This leaves the possibility that the bind may fail because the socket is already bound, but that probably just means that we are the second homestead (and are about to exit anyway because we can't bind the HTTP socket). Matt and I discussed retrying the bind if it fails the first time, but I'm not sure that is even needed. If something has gone wrong and we can't bind for some unknown reason retrying may not help. We will lose homestead stats which will be spotted by the EMS and someone can manually clear things up.

**Comment by mirw** [comment] 2015-01-20 09:40
I can't see why we *shouldn't* retry the bind if it fails the first time.  I'm always nervous of any failure mode where we have to rely on "someone manually clearing things up" - as someone who used to do 24x7 support, it's always better to recover automatically.

**Comment by AlexHockey** [comment] 2015-01-20 11:35
I don't think retrying *will* recover anything automatically. But it looks like retrying the bind won't be that hard so we might as well do it anyway.

**Comment by AlexHockey** [comment] 2015-01-20 14:18
So not unlinking the socket before binding works, but it creates another issue: homestead-prov uses the same socket. So if it starts up first it will prevent homestead from binding. Fix is to make homestead prov use a different socket (`/var/run/clearwater/stats/homestead-prov`). 

However in verifying this issue I have discovered that there is no need for homestead to retry the bind - zmq will handle it for us. I confirmed this as follows:
*  Start homestead-prov then homestead. No stats SNMP are returned when using snmpwalk, even after polling homestead. 
* Stop homestead-prov. Ping homestead. Now stats are returned by snmpwalk.

**Comment by AlexHockey** [comment] 2015-01-20 17:39
I may have spoken too soon - not unlinking the socket doesn't seem to work after all (presumably I messed up my earlier testing somehow). I have tried a fix where the LVC does not call `unlink` before `zmq_bind`. If I start a second copy of homestead the socket's inode is changed. I think `zmq_bind` is to blame, and that it's intentional. From the [ZMQ guide](http://zguide.zeromq.org/page:all#Plugging-Sockets-into-the-Topology):

"With most transports, you cannot bind to the same endpoint twice, unlike for example in UDP. The ipc transport does, however, let one process bind to an endpoint already used by a first process. It's meant to allow a process to recover after a crash."

I think the only solution is to start the LVC after homestead has bound it's TCP sockets. This only works if the process uses TCP sockets but all of our processes currently do anyway.

**Comment by dtheobald** [comment] 2015-01-20 18:41
On my CC build I temporarily changed PROCESS_NAME to "homestead-prov" in crest/homestead.local_settings/local_settings.py and now I get homestead statistics... Riddle me this - Why is homestead-prov setting up to send statistics, yet there doesn't seemed to any defined in the MIB?

**Comment by AlexHockey** [comment] 2015-01-20 19:48
This is historical really. We used to only publish stats over zmq (and used a special script to read them). homestead-prov used to have the functionality that is in homestead today, so it had a bunch of stats related to HSS and  HTTP interactions. When we introduced homestead we removed all the HSS stats from homestead-prov and left the HTTP ones. Then we added SNMP support but there wasn't much point in adding SNMP stats for homestead-prov; the HTTP stats aren't that useful for a provisioning API, and at the time homestead-prov wasn't even part of CC. However there was no point in removing the stats from the zmq interface so they have remained to this day.

**Comment by dtheobald** [comment] 2015-01-20 19:52
On a related topic - Why don't the "Scope" stats return a value? I was thinking that they should return length of the interval (in microseconds) over which the statistics are being collected.

**Comment by AlexHockey** [comment] 2015-01-20 20:12
Ahhh, this is starting to make more sense. I recently spun up a homestead node where monit incorrectly thought homestead-prov was not running and tried to restart it. This always failed (homestead-prov was alive and well). I had ignored this as the crest code does not explicitly unbind the socket, but I've since discovered that zmq does. The crest code starts the stats threads before it binds the listening socket.

So the "complex" scenario above could simply be:

* homestead starts and binds. 
* homestead-prov starts, blows away homestead's socket, creates a new one and binds. 
* snmpd starts and connects to homestead-prov's socket. It has connected to something (so doesn't retry) but it's the wrong thing so no stats come through. 

The "simple" scenario is then the above scenario, but with a rogue homestead-prov start at the end. It creates a new socket, then exits. If snmpd restarts the stats break as snmpd can't connect.

So my theory is that the issue is caused by homestead-prov starting when an instance is already running, not homestead. If this is the case a quick fix is just to change it's socket name (which I have a fix for). There is still an issue if hoemstead is started when it is already running, but I've not seen this happen personally. 

@mirw, is this analysis consistent with what you saw, or do you have evidence of homestead being started when it is already running?

**Comment by mirw** [comment] 2015-01-20 20:38
As discussed earlier, this analysis is consistent with what I saw.

However, I'm nervous about ignoring the homestead being restarted case.  It might lower the urgency but as we've shown, if it does happen (and there's nothing to stop it) it does cause this behavior.

**Comment by AlexHockey** [comment] 2015-01-21 10:04
Agreed, but I am trying to net down option given the currently proposed fix is a bit of a hack. 

Having said that I've read a bit more into lock files and they look like they would do what we need (crucially the lock a process holds is dropped when the FD is closed, which will happen on process exit). I am going to knock together a small test script to check this, and assuming all is well, implement this solution in the C++ code. For the crest code I'm probably just going to start the stats thread after binding the HTTP socket.

**Comment by AlexHockey** [comment] 2015-01-21 14:04
The current plan is to implement and test the fix to change the homestead-prov socket name, and come back to the multiple homestead problem later. I've started this but found stats were not working on an initial install. Investigation has showed #37 is the culprit.

**Comment by AlexHockey** [comment] 2015-01-21 15:37
OK, I've merged a couple of pull requests that should help with these issues:

* https://github.com/Metaswitch/crest/pull/187 fixes the biggest problem, that homestead and homestead-prov which means homestead-prov can break homestead's connection to snmpd. 
* https://github.com/Metaswitch/clearwater-infrastructure/pull/128 fixes a bug where stats do not work after a reboot. 

@dtheobald please could you take these PRs and see if they improve things (I think you have already done some testing with the first one). 

This still leaves the following problems:

* Stats don't work after an initial install. Covered by https://github.com/Metaswitch/clearwater-snmp-handlers/issues/37. Workaround is to restart snmpd. 
* If homestead is up and running and a second process gets started (which seems to happen occasionally with monit), the second process will exit but not before it recreates the unix socket. If snmpd restarts stats will stop working. Solution is to restart homestead. 

Assuming the PRs improve the situation, this isse will just cover the last bullet. The plan is to fix it using lock files, but I expect this is a less common failure mode and should have lower urgency.

**Comment by AlexHockey** [comment] 2015-01-23 10:05
Oops, should have assigned to Doug for retest.

**Comment by AlexHockey** [comment] 2015-02-25 10:36
@dtheobald I think the most serious problems uncovered in this issue are now fixed. Are you happy to downgrade to medium priority?

**Comment by dtheobald** [comment] 2015-02-25 15:06
Yes

**Comment by bossmc** [comment] 2015-07-06 15:58
@alango @rkd-msw - Can you check this is/will be fixed by the AgentX changes?  Either way, can you close this issue (and possibly raise a new one) please?

**Comment by rkd-msw** [comment] 2015-07-06 18:08
Yes, the AgentX changes fix this - I killed snmpd, and could query Bono stats again in under a minute. This is because AgentX subagents ping their master, and try to reconnect (http://www.net-snmp.org/docs/README.agentx.html).

**Closed by rkd-msw** 2015-07-06 18:08 UTC
Labels: cat:stability, medium-priority
