### ISSUE TITLE
Statistics don't work if some statistics don't change at least once every 5 seconds

### ISSUE THREAD

**Issue by mirw** [Metaswitch/clearwater-snmp-handlers#28] opened 2014-11-25 15:44 UTC
Sprout only publicizes statistics on value change, and only on the first request after a 5s interval if they are aggregated in this way.  This means that if the statistics do not change frequently enough, incorrect results are reported over SNMP.

**Comment by dtheobald** [comment] 2015-01-12 15:53
My comment from (closed as dup of this issue) #34 - SNMP statistic handler makes it look like the OID doesn't exist when no valid data is available; which is confusing since the OID actually still exists. In my experience OIDs like these don't come and go based on validity of data, they typically would return a published invalid value instead.

**Comment by mirw** [comment] 2015-01-12 17:49
I think the correct behavior here is **not** to return a published invalid value but to return the correct value (which is often likely to be something like 0).

@dtheobald, are you happy with this?

(I thought that's what we'd agreed on the other issue, but your latest comment suggests maybe not and I want to make sure we're in sync.)

**Comment by dtheobald** [comment] 2015-01-12 18:09
I think we agree... I was just leaving the door open for instances when a "correct" value is not possible. For instance, is it better to supply a "correct" latency value of zero (which may be misleading, if a latency of zero is not possible) or an "invalid" value that indicates something is wrong with the measurement. I don't know which is better... Perhaps a value of zero for a latency is "invalid" and everybody's happy.

**Comment by mirw** [comment] 2015-01-12 18:44
Fair point.  Can you outline the scenarios in which the statistic might be invalid?

*   If something is not installed or not configured, I think it's absolutely right to return "no such object".

*   If there were no instances of an event, some statistics aren't defined (e.g. latency).  In this case, I don't think we should return a magic value (e.g. INT_MAX) because this will ruin any graphs that are being plotted - I think 0 (or maybe "no such object") is appropriate.  (There is an associated "number of events" field that will report this situation.)

*   I can't immediately think of any other examples - can you?

**Comment by rkd-msw** [comment] 2015-06-09 11:20
Reopening - I don't think this is fixed, so it should be tracked and fixed in the upcoming stats work.

(@dtheobald, let me know if this is actually fixed and I just haven't spotted the change.)

**Comment by bossmc** [comment] 2015-07-06 17:19
@rkd-msw @alango - Can you check this one too?  Does the new SNMP architecture automatically "default" stats every time-period?

**Comment by rkd-msw** [comment] 2015-07-06 17:20
Yeah, this is fixed by design, and clearwater-fv-test tests this case.

**Closed by rkd-msw** 2015-07-06 17:20 UTC
Labels: bug, medium-priority
